#!/usr/bin/env bash -eu -o pipefail

set -x

namespace=whale
component=${1}
domain=${2}
env_name=$(terraform -chdir=terraform output -raw env_name)
tls_secret_name=${env_name}-${component}-tls
profile=$(terraform -chdir=terraform output -raw profile)

CERTIFICATE_ARN=$(aws acm list-certificates \
    --profile "$profile" \
    --query CertificateSummaryList[].[CertificateArn,DomainName] \
    --output text | grep "${component}.${domain}" | cut -f1 | head -n 1)

aws acm delete-certificate \
  --profile "$profile" \
  --certificate-arn "$CERTIFICATE_ARN"

lb_hostname=$(kubectl get ingress -n whale ingress-whale-${component} -o json | \
    jq -r '.status.loadBalancer.ingress[0].hostname')

whale_hosted_zone_id=$(aws route53 list-hosted-zones | \
                     jq -r ".HostedZones[] | select(.name=\"${whale_domain}\") | .Id" | \
                     rev | cut -d '/' -f 1 | rev)


cat > tmp/change-batch-${component}.${whale_domain} <<EOF
{
  "Comment": "CREATE CNAME for ui.whale.kubekit.io",
  "Changes": [{
      "Action": "DELETE",
      "ResourceRecordSet": {
          "Name": "ui.whale.kubekit.io",
          "Type": "CNAME",
          "TTL": 300,
          "ResourceRecords": [{ "Value": "$lb_hostname" }]
      }
  }]
}
EOF

aws route53 change-resource-record-sets \
    --hosted-zone-id "$whale_hosted_zone_id" \
    --change-batch file://$(pwd)/tmp/change-batch-${component}.${whale_domain}
