apiVersion: apps/v1
kind: Deployment
metadata:
  name: whale-ui
  labels:
    app: whale
    component: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whale
      component: ui
  template:
    metadata:
      labels:
        app: whale
        component: ui
    spec:
      containers:
      - name: ui
        image: REGISTRY_URL:IMAGE_VERSION
        ports:
        - containerPort: 80
