apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: whale
  name: whale-ui
  labels:
    app: whale
    component: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whale
      component: ui
  template:
    metadata:
      labels:
        app: whale
        component: ui
    spec:
      containers:
      - name: ui
        image: REGISTRY_URL:IMAGE_VERSION
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: whale
  name: whale-ui
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: whale
    component: ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: whale
  name: whale-ui
  annotations:
    # Empty until we create the certificate in ACM as per README
    alb.ingress.kubernetes.io/certificate-arn: ""
    alb.ingress.kubernetes.io/group.name: "whale"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-type: ip
    cert-manager.io/cluster-issuer: whale-prod
    kubernetes.io/ingress.class: alb
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - ui.whale.kubekit.io
      secretName: whale-prod-ui-tls
  rules:
    - host: ui.whale.kubekit.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whale-ui
                port:
                  number: 80
